### ISSUE TITLE
Issue with coordinates on zipcode 80226 Lakewood CO

### ISSUE THREAD

**Issue by jlariza** [seanpianka/Zipcodes#3]
Good day,

I am using the library to get the coordinates of a zipcode and retrieve the closest location from a database. 

I'm having an issue with zipcode `80226` for Lakewood, CO. Its coordinates are incorrect and it is generating problems.

This is the output I get:

```
zip_info = zipcodes.matching("80226")
[{'active': True,
  'city': 'DENVER',
  'country': 'US',
  'lat': 39.76,
  'long': -104.87,
  'state': 'CO',
  'world_region': 'NA',
  'zip_code': '80226',
  'zip_code_type': 'STANDARD'}]
```

But when I get that point on google maps, I am getting a point 12 miles further than Lakewood.

![image](https://user-images.githubusercontent.com/16421045/56053341-73cea980-5d19-11e9-9854-58e3cbfdc0ab.png)

Could you please check if the zipcodes database are updated and correct?

Thank you,

**Comment by seanpianka** [comment]
Hello @jlariza,

The zipcodes data file used in this project was compiled from the free version of the zipcode information packaged provided [here](https://www.unitedstateszipcodes.org/zip-code-database/). As stated within the free version of the download, the coordinate information is approximate and is _not_ precise (this is an intentional feature of the free version).

I apologize for the trouble caused, however no fix can be made unless a free data source is provided with precise coordinate data.

**Comment by seanpianka** [comment]
In the latest version, I have used a different, freely-available zipcode database to provide _hopefully_ more accurate GPS coordinates. Please let me know if you continue to have issues. Thanks!
